name: build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-24.04-arm
            arch: arm64
          - os: macos-15-intel
            arch: x64
          - os: macos-latest
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - run: make -j$(nproc || sysctl -n hw.ncpu)
      - run: make -j$(nproc || sysctl -n hw.ncpu) -C api-test
